<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CalculatorImpl" targetNamespace="http://impl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:portType name="CalculatorImplPortType">
  </wsdl:portType>
  <wsdl:binding name="CalculatorImplSoapBinding" type="tns:CalculatorImplPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="CalculatorImpl">
    <wsdl:port name="CalculatorImplPort" binding="tns:CalculatorImplSoapBinding">
      <soap:address location="http://localhost:8080/RESTCalculator/services/CalculatorImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
